services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5412:5432"
    networks:
      - db-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
      ADMINER_DESIGN: dracula
    networks:
      - db-network

  redis:
    image: redis:7
    container_name: redis_
    ports:
      - "6379:6379"
    networks:
      - db-network
    restart: unless-stopped
    volumes:
      - redis:/data

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis

  flower:
    image: mher/flower
    command: celery -A core flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis


networks:
  db-network:

volumes:
  postgres_data:
  redis:
