[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = "(venv/|proto_out/|.*__init__\\.py$)"
ignore_missing_imports = false


[tool.black]
line-length = 85
target-version = ["py311"]
skip-string-normalization = false
exclude = "(venv/|proto_out/|.*__init__\\.py$)"
